/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

/**
 *
 * @author 0030481711016
 */
public class frmCurso extends javax.swing.JFrame {

    /**
     * Creates new form GuiCurso
     */
    public frmCurso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSiglaCurso = new javax.swing.JLabel();
        lblNomeCurso = new javax.swing.JLabel();
        lblCargaHor = new javax.swing.JLabel();
        lblValorCurso = new javax.swing.JLabel();
        lblProgCurso = new javax.swing.JLabel();
        txtSiglaCurso = new javax.swing.JTextField();
        txtNomeCurso = new javax.swing.JTextField();
        txtCargaHor = new javax.swing.JTextField();
        txtValCurso = new javax.swing.JTextField();
        txtProgCurso = new javax.swing.JTextField();
        lblDataVigencia = new javax.swing.JLabel();
        txtDataVig = new javax.swing.JFormattedTextField();
        lblDataVigencia1 = new javax.swing.JLabel();
        txtDataVig1 = new javax.swing.JFormattedTextField();
        btnConsultar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastrar Curso");
        setMinimumSize(new java.awt.Dimension(586, 250));
        setName("frmCurso"); // NOI18N
        setPreferredSize(new java.awt.Dimension(586, 230));
        setResizable(false);
        setSize(new java.awt.Dimension(586, 230));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSiglaCurso.setText("Sigla curso");
        getContentPane().add(lblSiglaCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 31, -1, -1));

        lblNomeCurso.setText("Nome curso");
        getContentPane().add(lblNomeCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 57, -1, -1));

        lblCargaHor.setText("Carga horária");
        getContentPane().add(lblCargaHor, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 83, -1, -1));

        lblValorCurso.setText("Valor curso");
        getContentPane().add(lblValorCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 109, -1, -1));

        lblProgCurso.setText("Programa do curso");
        getContentPane().add(lblProgCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 135, -1, -1));
        getContentPane().add(txtSiglaCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 28, 71, -1));

        txtNomeCurso.setEnabled(false);
        getContentPane().add(txtNomeCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 54, 140, -1));

        txtCargaHor.setEnabled(false);
        getContentPane().add(txtCargaHor, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 80, 140, -1));

        txtValCurso.setEnabled(false);
        getContentPane().add(txtValCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 106, 70, -1));

        txtProgCurso.setEnabled(false);
        getContentPane().add(txtProgCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 132, 140, -1));

        lblDataVigencia.setText("Data de vigência");
        getContentPane().add(lblDataVigencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 83, -1, -1));

        try {
            txtDataVig.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataVig.setEnabled(false);
        getContentPane().add(txtDataVig, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 80, 123, -1));

        lblDataVigencia1.setText("Valor hora instrutor");
        getContentPane().add(lblDataVigencia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 109, -1, -1));

        txtDataVig1.setEnabled(false);
        txtDataVig1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataVig1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtDataVig1, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 106, 123, -1));

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 180, -1, -1));

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        getContentPane().add(btnInserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 180, 99, -1));

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 180, 99, -1));

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 180, 99, -1));

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 180, 99, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDataVig1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataVig1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataVig1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel lblCargaHor;
    private javax.swing.JLabel lblDataVigencia;
    private javax.swing.JLabel lblDataVigencia1;
    private javax.swing.JLabel lblNomeCurso;
    private javax.swing.JLabel lblProgCurso;
    private javax.swing.JLabel lblSiglaCurso;
    private javax.swing.JLabel lblValorCurso;
    private javax.swing.JTextField txtCargaHor;
    private javax.swing.JFormattedTextField txtDataVig;
    private javax.swing.JFormattedTextField txtDataVig1;
    private javax.swing.JTextField txtNomeCurso;
    private javax.swing.JTextField txtProgCurso;
    private javax.swing.JTextField txtSiglaCurso;
    private javax.swing.JTextField txtValCurso;
    // End of variables declaration//GEN-END:variables
}
