/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

/**
 *
 * @author 0030481711010
 */
public class frmEfetuarMat extends javax.swing.JFrame {

    /**
     * Creates new form frmEfetuarMat
     */
    public frmEfetuarMat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDtMatricula = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        lblTurma = new javax.swing.JLabel();
        lblCPFAluno = new javax.swing.JLabel();
        cmbCurso = new javax.swing.JComboBox<>();
        cmbTurma = new javax.swing.JComboBox<>();
        txtCPFAluno = new javax.swing.JFormattedTextField();
        txtDtMatricula = new javax.swing.JFormattedTextField();
        lblValor = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rbtnAVista = new javax.swing.JRadioButton();
        rbtnParcelado = new javax.swing.JRadioButton();
        lblAgencia = new javax.swing.JLabel();
        lblQtdeMensal = new javax.swing.JLabel();
        txtAgencia = new javax.swing.JTextField();
        txtQtdeMensal = new javax.swing.JTextField();
        lblNCheque = new javax.swing.JLabel();
        lblTxJuros = new javax.swing.JLabel();
        txtNCheque = new javax.swing.JTextField();
        txtTxJuros = new javax.swing.JTextField();
        lblDtPagto = new javax.swing.JLabel();
        txtDtPagto = new javax.swing.JFormattedTextField();
        lxlDtVencto = new javax.swing.JLabel();
        txtDtVencto = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Efetuar Matrícula");

        lblDtMatricula.setText("Data da Matrícula");

        lblCurso.setText("Curso");

        lblTurma.setText("Turma");

        lblCPFAluno.setText("CPF Aluno");

        try {
            txtCPFAluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtDtMatricula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        lblValor.setText("Valor");

        lblNome.setText("Nome");

        txtNome.setEnabled(false);

        txtValor.setEnabled(false);

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultar.setText("Consultar");

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pagamento"));

        rbtnAVista.setText("À Vista");
        rbtnAVista.setEnabled(false);

        rbtnParcelado.setText("Parcelado");
        rbtnParcelado.setEnabled(false);

        lblAgencia.setText("Agência");

        lblQtdeMensal.setText("Qtde. Mensalidades");

        txtAgencia.setEnabled(false);

        txtQtdeMensal.setEnabled(false);

        lblNCheque.setText("No. Cheque");

        lblTxJuros.setText("Tx. Juros(%)");

        txtNCheque.setEnabled(false);

        txtTxJuros.setEnabled(false);

        lblDtPagto.setText("Data Pagto.");

        try {
            txtDtPagto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDtPagto.setEnabled(false);

        lxlDtVencto.setText("Data 1o. Vencto.");

        try {
            txtDtVencto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDtVencto.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnAVista)
                    .addComponent(rbtnParcelado))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblAgencia)
                        .addGap(10, 10, 10)
                        .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(lblNCheque)
                        .addGap(10, 10, 10)
                        .addComponent(txtNCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(lblDtPagto)
                        .addGap(10, 10, 10)
                        .addComponent(txtDtPagto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblQtdeMensal)
                        .addGap(10, 10, 10)
                        .addComponent(txtQtdeMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(lblTxJuros)
                        .addGap(10, 10, 10)
                        .addComponent(txtTxJuros, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(lxlDtVencto)
                        .addGap(10, 10, 10)
                        .addComponent(txtDtVencto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnAVista)
                    .addComponent(lblAgencia)
                    .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNCheque)
                    .addComponent(txtNCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDtPagto)
                    .addComponent(txtDtPagto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnParcelado)
                    .addComponent(lblQtdeMensal)
                    .addComponent(txtQtdeMensal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTxJuros)
                    .addComponent(txtTxJuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lxlDtVencto)
                    .addComponent(txtDtVencto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        rbtnAVista.getAccessibleContext().setAccessibleName("rbtnAVista");
        rbtnParcelado.getAccessibleContext().setAccessibleName("rbtnParcelado");
        lblAgencia.getAccessibleContext().setAccessibleName("lblAgencia");
        lblQtdeMensal.getAccessibleContext().setAccessibleName("lblQtdeMensal");
        txtAgencia.getAccessibleContext().setAccessibleName("txtAgencia");
        txtAgencia.getAccessibleContext().setAccessibleDescription("");
        txtQtdeMensal.getAccessibleContext().setAccessibleName("txtQtdeMensal");
        lblNCheque.getAccessibleContext().setAccessibleName("lblNCheque");
        lblTxJuros.getAccessibleContext().setAccessibleName("lblTxJuros");
        txtNCheque.getAccessibleContext().setAccessibleName("txtNCheque");
        txtTxJuros.getAccessibleContext().setAccessibleName("txtTxJuros");
        lblDtPagto.getAccessibleContext().setAccessibleName("lblDtPagto");
        txtDtPagto.getAccessibleContext().setAccessibleName("txtDtPagto");
        lxlDtVencto.getAccessibleContext().setAccessibleName("lxlDtVencto");
        txtDtVencto.getAccessibleContext().setAccessibleName("txtDtVencto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnConsultar)
                        .addGap(30, 30, 30)
                        .addComponent(btnInserir)
                        .addGap(30, 30, 30)
                        .addComponent(btnAlterar)
                        .addGap(30, 30, 30)
                        .addComponent(btnExcluir)
                        .addGap(30, 30, 30)
                        .addComponent(btnSair))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDtMatricula)
                                .addGap(25, 25, 25)
                                .addComponent(txtDtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCurso)
                                            .addComponent(lblTurma))
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCPFAluno)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtCPFAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNome)
                                        .addGap(15, 15, 15)
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblValor)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDtMatricula)
                    .addComponent(txtDtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCurso))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTurma))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCPFAluno)
                            .addComponent(txtCPFAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblValor)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNome)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addGap(20, 20, 20))
        );

        lblDtMatricula.getAccessibleContext().setAccessibleName("lblDtMatricula");
        lblCurso.getAccessibleContext().setAccessibleName("lblCurso");
        lblTurma.getAccessibleContext().setAccessibleName("lblTurma");
        lblCPFAluno.getAccessibleContext().setAccessibleName("lblCPFAluno");
        cmbCurso.getAccessibleContext().setAccessibleName("cmbCurso");
        cmbTurma.getAccessibleContext().setAccessibleName("cmbTurma");
        txtCPFAluno.getAccessibleContext().setAccessibleName("txtCPFAluno");
        txtDtMatricula.getAccessibleContext().setAccessibleName("txtDtMatricula");
        lblValor.getAccessibleContext().setAccessibleName("lblValor");
        lblValor.getAccessibleContext().setAccessibleDescription("");
        lblNome.getAccessibleContext().setAccessibleName("lblNome");
        txtNome.getAccessibleContext().setAccessibleName("txtNome");
        txtValor.getAccessibleContext().setAccessibleName("txtValor");
        btnConsultar.getAccessibleContext().setAccessibleName("btnConsultar");
        btnInserir.getAccessibleContext().setAccessibleName("btnInserir");
        btnAlterar.getAccessibleContext().setAccessibleName("btnAlterar");
        btnExcluir.getAccessibleContext().setAccessibleName("btnExcluir");
        btnSair.getAccessibleContext().setAccessibleName("btnSair");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEfetuarMat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEfetuarMat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEfetuarMat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEfetuarMat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEfetuarMat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cmbCurso;
    private javax.swing.JComboBox<String> cmbTurma;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAgencia;
    private javax.swing.JLabel lblCPFAluno;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblDtMatricula;
    private javax.swing.JLabel lblDtPagto;
    private javax.swing.JLabel lblNCheque;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblQtdeMensal;
    private javax.swing.JLabel lblTurma;
    private javax.swing.JLabel lblTxJuros;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lxlDtVencto;
    private javax.swing.JRadioButton rbtnAVista;
    private javax.swing.JRadioButton rbtnParcelado;
    private javax.swing.JTextField txtAgencia;
    private javax.swing.JFormattedTextField txtCPFAluno;
    private javax.swing.JFormattedTextField txtDtMatricula;
    private javax.swing.JFormattedTextField txtDtPagto;
    private javax.swing.JFormattedTextField txtDtVencto;
    private javax.swing.JTextField txtNCheque;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtQtdeMensal;
    private javax.swing.JTextField txtTxJuros;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
