/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

/**
 *
 * @author 0030481711046
 */
public class frmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuPrincipal
     */
    public frmMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCadastros = new javax.swing.JMenu();
        mnuCadCurso = new javax.swing.JMenuItem();
        mnuCadTurma = new javax.swing.JMenuItem();
        mnuCadInstrutor = new javax.swing.JMenuItem();
        mnuCadAluno = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuSair = new javax.swing.JMenuItem();
        mnuOperacoes = new javax.swing.JMenu();
        mnuOpeAlocInst = new javax.swing.JMenuItem();
        mnuOpeEfeMat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trabalho POO");

        mnuCadastros.setText("Cadastros");

        mnuCadCurso.setText("Curso");
        mnuCadCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadCursoActionPerformed(evt);
            }
        });
        mnuCadastros.add(mnuCadCurso);

        mnuCadTurma.setText("Turma");
        mnuCadTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadTurmaActionPerformed(evt);
            }
        });
        mnuCadastros.add(mnuCadTurma);

        mnuCadInstrutor.setText("Instrutor");
        mnuCadInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadInstrutorActionPerformed(evt);
            }
        });
        mnuCadastros.add(mnuCadInstrutor);

        mnuCadAluno.setText("Aluno");
        mnuCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadAlunoActionPerformed(evt);
            }
        });
        mnuCadastros.add(mnuCadAluno);
        mnuCadastros.add(jSeparator1);

        mnuSair.setText("Sair");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        mnuCadastros.add(mnuSair);

        jMenuBar1.add(mnuCadastros);

        mnuOperacoes.setText("Operações");

        mnuOpeAlocInst.setText("Alocar Instrutor");
        mnuOpeAlocInst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOpeAlocInstActionPerformed(evt);
            }
        });
        mnuOperacoes.add(mnuOpeAlocInst);

        mnuOpeEfeMat.setText("Efetuar Matrícula");
        mnuOpeEfeMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOpeEfeMatActionPerformed(evt);
            }
        });
        mnuOperacoes.add(mnuOpeEfeMat);

        jMenuBar1.add(mnuOperacoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCadCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadCursoActionPerformed
        frmCurso frm = new frmCurso();
        frm.setVisible(true);
    }//GEN-LAST:event_mnuCadCursoActionPerformed

    private void mnuCadTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadTurmaActionPerformed
        frmTurma frm = new frmTurma();
        frm.setVisible(true);
    }//GEN-LAST:event_mnuCadTurmaActionPerformed

    private void mnuCadInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadInstrutorActionPerformed
        frmInstrutor frm = new frmInstrutor();
        frm.setVisible(true);
    }//GEN-LAST:event_mnuCadInstrutorActionPerformed

    private void mnuCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadAlunoActionPerformed
        frmAluno frm = new frmAluno();
        frm.setVisible(true);
    }//GEN-LAST:event_mnuCadAlunoActionPerformed

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        dispose();
    }//GEN-LAST:event_mnuSairActionPerformed

    private void mnuOpeAlocInstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOpeAlocInstActionPerformed
        frmAlocarInst frm = new frmAlocarInst();
        frm.setVisible(true);
    }//GEN-LAST:event_mnuOpeAlocInstActionPerformed

    private void mnuOpeEfeMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOpeEfeMatActionPerformed
        frmEfetuarMat frm = new frmEfetuarMat();
        frm.setVisible(true);
    }//GEN-LAST:event_mnuOpeEfeMatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem mnuCadAluno;
    private javax.swing.JMenuItem mnuCadCurso;
    private javax.swing.JMenuItem mnuCadInstrutor;
    private javax.swing.JMenuItem mnuCadTurma;
    private javax.swing.JMenu mnuCadastros;
    private javax.swing.JMenuItem mnuOpeAlocInst;
    private javax.swing.JMenuItem mnuOpeEfeMat;
    private javax.swing.JMenu mnuOperacoes;
    private javax.swing.JMenuItem mnuSair;
    // End of variables declaration//GEN-END:variables
}
